/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5my9n2bbQj6
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Syne } from 'next/font/google'
import { Gabarito } from 'next/font/google'

syne({
  subsets: ['latin'],
  display: 'swap',
})

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function OurTeam() {
  return (
    <div className="bg-muted text-muted-foreground p-6 md:p-10 rounded-lg">
      <div className="container mx-auto max-w-5xl">
        <div className="flex flex-col items-center justify-center space-y-8">
          <div className="space-y-2 text-center">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Our Dedicated Team</h1>
            <p className="max-w-[700px] text-muted-foreground md:text-xl">
              Meet the passionate individuals behind our mental health support services.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 w-full">
            <div className="bg-background rounded-lg p-6 flex flex-col items-center text-center space-y-4">
              <div className="rounded-full w-24 h-24 overflow-hidden">
                <img src="/placeholder.svg" alt="John Doe" className="w-full h-full object-cover" />
              </div>
              <div>
                <h3 className="text-xl font-semibold">John Doe</h3>
                <p className="text-muted-foreground">Founder & CEO</p>
              </div>
              <p className="text-muted-foreground">
                John is the driving force behind our mission to provide accessible mental health support.
              </p>
            </div>
            <div className="bg-background rounded-lg p-6 flex flex-col items-center text-center space-y-4">
              <div className="rounded-full w-24 h-24 overflow-hidden">
                <img src="/placeholder.svg" alt="Jane Smith" className="w-full h-full object-cover" />
              </div>
              <div>
                <h3 className="text-xl font-semibold">Jane Smith</h3>
                <p className="text-muted-foreground">Clinical Director</p>
              </div>
              <p className="text-muted-foreground">
                Jane oversees our clinical team and ensures the highest quality of care for our clients.
              </p>
            </div>
            <div className="bg-background rounded-lg p-6 flex flex-col items-center text-center space-y-4">
              <div className="rounded-full w-24 h-24 overflow-hidden">
                <img src="/placeholder.svg" alt="Michael Johnson" className="w-full h-full object-cover" />
              </div>
              <div>
                <h3 className="text-xl font-semibold">Michael Johnson</h3>
                <p className="text-muted-foreground">Lead Therapist</p>
              </div>
              <p className="text-muted-foreground">
                Michael leads our team of experienced therapists, ensuring high-quality care for our clients.
              </p>
            </div>
            <div className="bg-background rounded-lg p-6 flex flex-col items-center text-center space-y-4">
              <div className="rounded-full w-24 h-24 overflow-hidden">
                <img src="/placeholder.svg" alt="Emily Davis" className="w-full h-full object-cover" />
              </div>
              <div>
                <h3 className="text-xl font-semibold">Emily Davis</h3>
                <p className="text-muted-foreground">Community Manager</p>
              </div>
              <p className="text-muted-foreground">
                Emily fosters a supportive community for our clients, organizing events and facilitating group sessions.
              </p>
            </div>
            <div className="bg-background rounded-lg p-6 flex flex-col items-center text-center space-y-4">
              <div className="rounded-full w-24 h-24 overflow-hidden">
                <img src="/placeholder.svg" alt="David Lee" className="w-full h-full object-cover" />
              </div>
              <div>
                <h3 className="text-xl font-semibold">David Lee</h3>
                <p className="text-muted-foreground">Operations Manager</p>
              </div>
              <p className="text-muted-foreground">
                David ensures the smooth running of our organization, managing logistics and operations.
              </p>
            </div>
            <div className="bg-background rounded-lg p-6 flex flex-col items-center text-center space-y-4">
              <div className="rounded-full w-24 h-24 overflow-hidden">
                <img src="/placeholder.svg" alt="Sarah Chen" className="w-full h-full object-cover" />
              </div>
              <div>
                <h3 className="text-xl font-semibold">Sarah Chen</h3>
                <p className="text-muted-foreground">Marketing Manager</p>
              </div>
              <p className="text-muted-foreground">
                Sarah leads our marketing efforts, raising awareness and connecting with our community.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
